name: Build image

on:
  push:
    branches: [main]

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Variable
        id: set-env
        run: |
          TAG=$(git describe --tags --abbrev=0 --match 'v*' 2> /dev/null) || true
          if [ -z "$TAG" ]; then
            echo "No tag found, use v0.0.1 as default"
            TAG=v0.0.1
          fi
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "DATE=$(TZ=Asia/Shanghai date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Show Variable
        run: echo "varibables ${{ steps.set-env.outputs.TAG }}-${{ steps.set-env.outputs.DATE }}"
      - name: Login to the dockerhub Registry
        uses: docker/login-action@v2
        with:
          username: abirdcfly
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: benjlevesque/short-sha@v2.1
        name: Get short commit sha
        id: short-sha
      - name: Build and push
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          tags: |
            abirdcfly/chatbot:latest
            abirdcfly/chatbot:${{ steps.set-env.outputs.TAG }}
            abirdcfly/chatbot:v${{ steps.set-env.outputs.DATE }}-${{ steps.short-sha.outputs.sha }}
            abirdcfly/chatbot:${{ steps.set-env.outputs.TAG }}-${{ steps.set-env.outputs.DATE }}-${{ steps.short-sha.outputs.sha }}
          push: true